import type { ModelProfile } from "../domain/types.js";

export const modelRegistry: ModelProfile[] = [
  {
    id: "openai-fast",
    provider: "openai",
    apiModelEnv: "OPENAI_FAST_MODEL_ID",
    label: "Fast model",
    capabilities: [
      "classification",
      "summarization",
      "translation",
      "structured-output",
      "tool-selection",
      "light-code",
    ],
    modalities: ["text", "file", "code"],
    maxContextTokens: 128_000,
    toolUse: true,
    structuredOutput: true,
    reasoningLevel: "moderate",
    reliability: 0.84,
    costTier: 1,
    latencyTier: 1,
    privacySupport: ["public", "internal", "confidential"],
    enabled: true,
  },
  {
    id: "openai-balanced",
    provider: "openai",
    apiModelEnv: "OPENAI_BALANCED_MODEL_ID",
    label: "Balanced reasoning model",
    capabilities: [
      "classification",
      "planning",
      "reasoning",
      "coding",
      "vision",
      "document-analysis",
      "structured-output",
      "tool-selection",
      "tool-use",
      "research",
      "data-analysis",
      "document-authoring",
    ],
    modalities: ["text", "image", "file", "code"],
    maxContextTokens: 256_000,
    toolUse: true,
    structuredOutput: true,
    reasoningLevel: "complex",
    reliability: 0.93,
    costTier: 2,
    latencyTier: 2,
    privacySupport: ["public", "internal", "confidential", "restricted"],
    enabled: true,
  },
  {
    id: "openai-frontier",
    provider: "openai",
    apiModelEnv: "OPENAI_FRONTIER_MODEL_ID",
    label: "Frontier reasoning model",
    capabilities: [
      "classification",
      "planning",
      "deep-reasoning",
      "coding",
      "architecture",
      "vision",
      "document-analysis",
      "structured-output",
      "tool-selection",
      "tool-use",
      "research",
      "security-analysis",
      "multi-agent-synthesis",
      "data-analysis",
      "document-authoring",
    ],
    modalities: ["text", "image", "file", "code"],
    maxContextTokens: 512_000,
    toolUse: true,
    structuredOutput: true,
    reasoningLevel: "expert",
    reliability: 0.98,
    costTier: 4,
    latencyTier: 4,
    privacySupport: ["public", "internal", "confidential", "restricted"],
    enabled: true,
  },
  {
    id: "local-private",
    provider: "local",
    apiModelEnv: "LOCAL_MODEL_ID",
    label: "Local private model",
    capabilities: ["classification", "summarization", "structured-output", "privacy"],
    modalities: ["text", "file"],
    maxContextTokens: 64_000,
    toolUse: false,
    structuredOutput: true,
    reasoningLevel: "moderate",
    reliability: 0.72,
    costTier: 1,
    latencyTier: 2,
    privacySupport: ["public", "internal", "confidential", "restricted"],
    enabled: false,
  },
];
