import type { SkillProfile } from "../domain/types.js";

export const skillRegistry: SkillProfile[] = [
  {
    id: "web-search",
    label: "Web Search",
    description: "Retrieves fresh public information and source citations.",
    domains: ["general", "research", "news", "travel", "law", "technology"],
    capabilities: ["fresh-data", "retrieval", "citations", "fact-checking"],
    inputModalities: ["text"],
    outputModalities: ["text", "file"],
    sideEffect: "none",
    riskCeiling: "high",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 2,
    tags: ["read-only", "freshness"],
  },
  {
    id: "github",
    label: "GitHub",
    description: "Reads or changes repositories, issues, pull requests, and workflows.",
    domains: ["software", "devops", "security"],
    capabilities: ["repository-read", "repository-write", "code-review", "issue-management"],
    inputModalities: ["text", "code", "file"],
    outputModalities: ["text", "code", "file"],
    sideEffect: "reversible",
    riskCeiling: "high",
    requiresAuth: true,
    enabled: true,
    costTier: 1,
    latencyTier: 2,
    tags: ["connector", "approval-on-write"],
  },
  {
    id: "code-execution",
    label: "Code Execution",
    description: "Runs deterministic calculations, tests, transformations, and validation.",
    domains: ["software", "data", "math", "general"],
    capabilities: ["calculation", "testing", "code-execution", "data-analysis"],
    inputModalities: ["text", "code", "file"],
    outputModalities: ["text", "code", "file", "image"],
    sideEffect: "reversible",
    riskCeiling: "high",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 2,
    tags: ["sandbox", "deterministic"],
  },
  {
    id: "file-search",
    label: "File Search",
    description: "Searches user-provided files and private indexed documents.",
    domains: ["documents", "research", "general"],
    capabilities: ["private-retrieval", "document-analysis", "citations"],
    inputModalities: ["text", "file"],
    outputModalities: ["text"],
    sideEffect: "none",
    riskCeiling: "high",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 1,
    tags: ["read-only", "private-data"],
  },
  {
    id: "image-generation",
    label: "Image Generation",
    description: "Creates or edits images from textual and visual instructions.",
    domains: ["design", "marketing", "general"],
    capabilities: ["image-generation", "image-editing", "visual-design"],
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    sideEffect: "none",
    riskCeiling: "medium",
    requiresAuth: false,
    enabled: true,
    costTier: 2,
    latencyTier: 3,
    tags: ["creative"],
  },
  {
    id: "document-builder",
    label: "Document Builder",
    description: "Creates and edits structured business or academic documents.",
    domains: ["documents", "academic", "business", "legal"],
    capabilities: ["document-authoring", "formatting", "export"],
    inputModalities: ["text", "file"],
    outputModalities: ["file", "text"],
    sideEffect: "reversible",
    riskCeiling: "high",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 2,
    tags: ["artifact"],
  },
  {
    id: "spreadsheet-builder",
    label: "Spreadsheet Builder",
    description: "Builds, repairs, and analyzes spreadsheets with formulas and charts.",
    domains: ["data", "finance", "business", "general"],
    capabilities: ["spreadsheet", "calculation", "data-analysis", "export"],
    inputModalities: ["text", "file"],
    outputModalities: ["file", "image", "text"],
    sideEffect: "reversible",
    riskCeiling: "high",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 2,
    tags: ["artifact", "deterministic"],
  },
  {
    id: "human-approval",
    label: "Human Approval",
    description: "Pauses execution before sensitive, destructive, financial, or public actions.",
    domains: ["general"],
    capabilities: ["approval", "risk-control"],
    inputModalities: ["text"],
    outputModalities: ["text"],
    sideEffect: "none",
    riskCeiling: "critical",
    requiresAuth: false,
    enabled: true,
    costTier: 1,
    latencyTier: 1,
    tags: ["safety"],
  },
];
